### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by naveenland4** [mhdzumair/tamilyogi_streamio_addon#1]
Hello bro,

Could you please assist me in how to install this addon in Streamio in Android TV after the App is installed?

**Comment by mhdzumair** [comment]
Hi @naveenland4 , streamio doesn't support http link to be used as video source when the add-on is published. But this add-on can be setup on local machine and can be used with streamio. Thanks for querying this add-on.

If you really need a Tamil film add-on for streamio, then I can make a separate add-on with another torrent based popular site.

**Comment by naveenland4** [comment]
Thanks for your response bro… if possible can you pls do one for tamil movies… thanks in advance…

**Comment by mhdzumair** [comment]
Hi @naveenland4 its been a while, i was able to publish this addon with a limitation. you can read it on README. 
Also i started to work on another addon https://github.com/mhdzumair/tamilblasters_streamio_addon. i will publish that ASAP.

**Comment by naveenland4** [comment]
Thanks bro. Added it to Stremio. Thanks for your work… cheers….

**Comment by mhdzumair** [comment]
Let me know if it is working for you.

**Comment by naveenland4** [comment]
> Let me know if it is working for you.

Tamil yogi works fine with external player bro… tamil blaster doesnt work properly

**Comment by mhdzumair** [comment]
R u using in mobile or android tv? Tamil blaster won't work now. I need to migrate the deployment to vercel. Ill update the readme for tamil blaster when its ready to use.

**Comment by naveenland4** [comment]
> 

Am using both in my firestick and android tv bro

**Comment by AmongCrysis** [comment]
> > Let me know if it is working for you.
> 
> Tamil yogi works fine with external player bro… tamil blaster doesnt work properly 

What external player are you using and does it work on android TV?
