### ISSUE TITLE
Tamilyogi

### ISSUE THREAD

**Issue by sadamshajahan** [mhdzumair/tamilyogi_streamio_addon#6]
I use tamil yogi in my andriod tv. It shows only the catalog. When I click any movie or series, it loads and shows no streams from tamil yogi. Any help please?

**Comment by sadamshajahan** [comment]
Hello,

I use your stremio add-ons and I absolutely love it. I'm wondering if there is an add-on for Tamildhool, a trendy website for TV shows. 

https://www.tamildhool.net/

Thanks,
Sadam

**Comment by mhdzumair** [comment]
There are some IP limitation even if im able to scrap the video link from tamildhool & tamilyogi. so that addon can only be able to set up in local. currently im only supporting https://github.com/mhdzumair/MediaFusion add-on
